### ISSUE TITLE
Date should be sorted on the database side otherwise sort isn't done across pagination.

### ISSUE THREAD

**Issue by cepitspace** [arshidkv12/contact-form-cfdb7#1]
When sorting by date it doesn't sort across pages but only the current page.

Example (probably shouldn't be used):

`$orderby = (isset($_GET['orderby'])) ? str_replace('-', '_', $_GET['orderby']) : 'form_date';
        $order = (isset($_GET['order'])) ? str_replace('-', '_', $_GET['order']) : 'asc';

        if ( ! empty($search) ) {

           $results = $cfdb->get_results( "SELECT * FROM $table_name WHERE  form_value LIKE '%$search%' ORDER BY `$orderby` $order LIMIT $start,10", OBJECT );
        }else{

            $results = $cfdb->get_results( "SELECT * FROM $table_name WHERE form_post_id = $form_post_id ORDER BY `$orderby` $order LIMIT $start,10", OBJECT );
        }`

**Comment by arshidkv12** [comment]
Thank you.
I will check it.

**Comment by arshidkv12** [comment]
It is fixed. (version 1.1.9)
