### ISSUE TITLE
Captcha Response 

### ISSUE THREAD

**Issue by gregorytoscano** [arshidkv12/contact-form-cfdb7#11]
![image](https://user-images.githubusercontent.com/25824781/38215090-9d34b08c-3694-11e8-9d58-fec149712533.png)

Is there anyway to not record the re-captcha response? Above is the image of my CSV

This is the Captcha we are using:
![image](https://user-images.githubusercontent.com/25824781/38215124-bc711e68-3694-11e8-8bd8-650df38c9d5c.png)

**Comment by arshidkv12** [comment]
Add following code in your theme **functions.php** 
 
```
add_filter('cfdb7_before_save_data', 'remove_captcha_cfdb7');
function remove_captcha_cfdb7( $form_data ){
  unset($form_data['G-recaptcha-response']);
   return $form_data;
}
```
