### ISSUE TITLE
New hook doesn't seems to work

### ISSUE THREAD

**Issue by atoupet-toki** [arshidkv12/contact-form-cfdb7#17]
**Describe the bug**
Tried to use the new hook `cfdb7_before_save` but the returned value doesn't seems to be used

**To Reproduce**
1. Create an hook that modify the content on the dataForm
2. Submit the form
3. Value registered is not the one that is modified

**Expected behavior**
Excpected to save the modified value (by the hook)

**Additional context**
Maybe also correct the SQL error syntax with accent characters <3

**Comment by arshidkv12** [comment]
Please use `cfdb7_before_save_data` hook.
