### ISSUE TITLE
reset the form_values

### ISSUE THREAD

**Issue by lixiaomeng8520** [arshidkv12/contact-form-cfdb7#26]
https://github.com/arshidkv12/contact-form-cfdb7/blob/70973f255e03a9523779d12359b12b5a12ab438f/inc/admin-subpage.php#L251

should reset the form_values here.

```
$form_values = [];
```

otherwise the old item without the new field will be override by the last item.

**Comment by arshidkv12** [comment]
What error you getting?

**Comment by lixiaomeng8520** [comment]
I added a new field in a form
 But the new field's value of the old item was not empty。

**Comment by arshidkv12** [comment]
Please note, please take backup then delete old submissions.

You can't add field without delete existing submissions.

Adding new field in production server is good idea.

**Comment by lixiaomeng8520** [comment]
OK
