### ISSUE TITLE
csv export column Issue

### ISSUE THREAD

**Issue by askingokyildiz** [arshidkv12/contact-form-cfdb7#28]
csv is exporting information in one column!
How can I save as multiple columns?
https://drive.google.com/file/d/1MdqGsZBHoLavAayxcQRKNEOtgZmN6vKU/view?usp=sharing

**Comment by arshidkv12** [comment]
Upload CSV to google drive and check it.

**Comment by askingokyildiz** [comment]
Are you talking about the export-csv.php file?

**Comment by arshidkv12** [comment]
Export CSV from wp-admin then upload to Google drive and check it. (If is
your CSV client issue)

**Comment by askingokyildiz** [comment]
https://drive.google.com/file/d/1NSuqPknkGRmfNpDdvvHIZrOJTvIXsa7B/view?usp=sharing

Why does it show up properly in google drive?
What should I do to make it display properly when I export?

**Comment by arshidkv12** [comment]
Change CSV client settings or purchase cfdb7 xlsx plugin

**Comment by askingokyildiz** [comment]
Thank you for the information.
