### ISSUE TITLE
UTF-8 is an invalid value for the Content-Encoding header

### ISSUE THREAD

**Issue by DinoChiesa** [arshidkv12/contact-form-cfdb7#35]
https://github.com/arshidkv12/contact-form-cfdb7/blob/7bb39c3903bbbe2548f8a664fc3b2318ce4ec1af/inc/export-csv.php#L24C37-L24C37

UTF-8 is [never a valid value](https://stackoverflow.com/a/17155003) for Content-Encoding.  So this line surely is in error. 

The nearby lines that repeatedly set Content-Type to three distinct values... are also wrong. There should be [one Content-Type](https://stackoverflow.com/a/64131906). But that is a separate bug.

**Comment by arshidkv12** [comment]
Done
