### ISSUE TITLE
Add action to database entries

### ISSUE THREAD

**Issue by ondics** [arshidkv12/contact-form-cfdb7#38]
Great plugin! 

I use this plugin (on top of cf7) to allow applications for events.
To manage applications I need an easy way for a quick feedback.

I thought about extending for form "cfdb7-list" in the function [form_details_page](https://github.com/arshidkv12/contact-form-cfdb7/blob/fe8c09437d4ab6940108d4352f62ffb2788ea3a9/inc/admin-form-details.php#L22C21-L22C38) 
with two buttons "positive feedback" and "negative feedback" and a textaera with text to send by email.

Is this a way to go or are there different strategies to achieve this goal?

**Comment by arshidkv12** [comment]
It needs custom plug. Please feel free to PM support@ciphercoin.com
